#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'English'

# check for whitespace errors
git_ws_check = `git diff-index --check --cached HEAD --`
unless $CHILD_STATUS.success?
  puts git_ws_check
  exit 1
end

COOKBOOK_PATH = File.split `git rev-parse --show-toplevel`
PARENT_PATH = COOKBOOK_PATH[0]
COOKBOOK_NAME = COOKBOOK_PATH[1].chomp # remove trailing newline

puts 'Running knife cookbook test...'
knife_output =
  `bundle exec knife cookbook test #{COOKBOOK_NAME} -o #{PARENT_PATH}`
unless $CHILD_STATUS.success?
  puts knife_output
  exit 1
end

puts 'Running tailor...'

# Get the file names of (A)dded, (C)opied, (M)odified Ruby files
STAGED_FILES = `git diff-index --name-only --diff-filter=ACM HEAD -- '*.rb'`
STAGED_FILES.lines do |file|
  file.chomp! # remove carriage returns
  puts file
  tailor_output = `bundle exec tailor --max-line-length 999 #{ file }`
  unless $CHILD_STATUS.success?
    puts tailor_output
    exit 1
  end
end

puts 'Running RuboCop...'
STAGED_FILES.lines do |file|
  file.chomp! # remove carriage returns
  puts file
  rubocop_output = `bundle exec rubocop #{ file }`
  unless $CHILD_STATUS.success?
    puts rubocop_output
    exit 1
  end
end

puts 'Running foodcritic...'
fc_output =
  `bundle exec foodcritic --epic-fail any #{File.join(COOKBOOK_PATH)}`
unless $CHILD_STATUS.success?
  puts fc_output
  exit 1
end
